# Generated by Django 5.2.12 on 2026-03-15 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=100)),
                ('application_mode', models.CharField(max_length=100)),
                ('application_order', models.IntegerField()),
                ('course', models.CharField(max_length=255)),
                ('daytime_evening_attendance', models.CharField(max_length=50)),
                ('previous_qualification', models.CharField(max_length=255)),
                ('nacionality', models.CharField(max_length=100)),
                ('mother_qualification', models.CharField(max_length=255)),
                ('father_qualification', models.CharField(max_length=255)),
                ('mother_occupation', models.CharField(max_length=255)),
                ('father_occupation', models.CharField(max_length=255)),
                ('displaced', models.BooleanField()),
                ('educational_special_needs', models.BooleanField()),
                ('debtor', models.BooleanField()),
                ('tuition_fees_up_to_date', models.BooleanField()),
                ('gender', models.CharField(max_length=10)),
                ('scholarship_holder', models.BooleanField()),
                ('age_at_enrollment', models.IntegerField()),
                ('international', models.BooleanField()),
                ('curricular_units_1st_sem_credited', models.IntegerField()),
                ('curricular_units_1st_sem_enrolled', models.IntegerField()),
                ('curricular_units_1st_sem_evaluations', models.IntegerField()),
                ('curricular_units_1st_sem_approved', models.IntegerField()),
                ('curricular_units_1st_sem_grade', models.FloatField()),
                ('curricular_units_1st_sem_without_evaluations', models.IntegerField()),
                ('curricular_units_2nd_sem_credited', models.IntegerField()),
                ('curricular_units_2nd_sem_enrolled', models.IntegerField()),
                ('curricular_units_2nd_sem_evaluations', models.IntegerField()),
                ('curricular_units_2nd_sem_approved', models.IntegerField()),
                ('curricular_units_2nd_sem_grade', models.FloatField()),
                ('curricular_units_2nd_sem_without_evaluations', models.IntegerField()),
                ('unemployment_rate', models.FloatField()),
                ('inflation_rate', models.FloatField()),
                ('gdp', models.FloatField()),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
