# Generated by Django 5.2.12 on 2026-03-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='target',
            field=models.CharField(blank=True, choices=[('Dropout', 'Dropout'), ('Graduate', 'Graduate'), ('Enrolled', 'Enrolled')], default='', max_length=20),
        ),
    ]
